# =================================================================
#
# Authors: Just van den Broecke <justb4@gmail.com>>
#          Jorge Samuel Mendes de Jesus <jorge.dejesus@geocat.net>
#          Tom Kraldis <tomkralidis@gmail.com>
#
# Copyright (c) 2019 Just van den Broecke
# Copyright (c) 2019 Jorge Samuel Mendes de Jesus
# Copyright (c) 2020 Tom Kralidis
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation
# files (the "Software"), to deal in the Software without
# restriction, including without limitation the rights to use,
# copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following
# conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
# =================================================================

server:
    bind:
        host: 0.0.0.0
        port: 5000
    url: http://localhost:5000/
    mimetype: application/json; charset=UTF-8
    encoding: utf-8
    gzip: false
    language: en-US
    cors: true
    pretty_print: true
    admin: ${PYGEOAPI_SERVER_ADMIN:-false}
    # limit: 1000
    limits:
        default_items: 100
        max_items: 500
    map:
        url: https://tile.openstreetmap.org/{z}/{x}/{y}.png
        attribution: '&copy; <a href="https://openstreetmap.org/copyright">OpenStreetMap contributors</a>'
    ogc_schemas_location: /schemas.opengis.net
    # manager:
    #     name: TinyDB
    #     connection: /tmp/pygeoapi-process-manager.db
    #     output_dir: /tmp/

logging:
    level: ERROR #INFO
    #logfile: /tmp/pygeoapi.log

metadata:
    identification:
        title: Demo pygeoapi instance voor OGC API Workshop
        description: Deze instance dient als MVP demo voor de OGC API workshop
        keywords:
            - geospatial
            - data
            - api
        keywords_type: theme
        terms_of_service: https://creativecommons.org/licenses/by/4.0/
        url: https://github.com/Geonovum/ogc-api-kennissessie/
    license:
        name: CC-BY 4.0 license
        url: https://creativecommons.org/licenses/by/4.0/
    provider:
        name: Geonovum Standaarden team
        url: https://geonovum.nl
    contact:
        name: Geonovum
        position: Standaarden Team
        address: Barchman Wuytierslaan 10
        city: Amersfoort
        stateorprovince: #
        postalcode: #
        country: Nederland
        phone: +xx-xxx-xxx-xxxx
        fax: +xx-xxx-xxx-xxxx
        email: info@geonovum.nl
        url: https://pygeoapi.io
        hours: 24/7
        instructions: During hours of service.
        role: pointOfContact

resources:
    # ==== demo OGC API Features ====
    knmi_meetstations:
        type: collection
        title: Meetstations
        description: knmi meetstations
        keywords:
            - observations
            - meetstations
        extents:
            spatial:
                # bbox: [3.37,50.75,7.21,53.47]
                bbox: [-68.5,55.7,7.4,12]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
        providers:
            - type: feature
              name: GeoJSON
              data: /data/knmi_meetstations.geojson
              id_field: STN

    buurten:
        type: collection
        title: Buurten
        description: Buurten Amstelveen
        keywords:
            - Gebiedsindeling
            - Gebieden
        extents:
            spatial:
                bbox: [3.37,50.75,7.21,53.47]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
        providers:
            - type: feature
              name: GeoJSON
              data: /data/buurten.geojson
              id_field: fid

